### ISSUE TITLE
Update Copy on VS Code Marketplace

### ISSUE THREAD

**Issue by gregnist** [marklogic/mlxprs#39] opened 2020-04-15 12:41 UTC
These are some suggestions I would make for changes to how this is presented on VS Code Marketplace. Please see the annotated image:

![Suggested-VSCode-Marketplace-Changes](https://user-images.githubusercontent.com/1749707/79338118-b3177380-7ef4-11ea-85ee-f420416e0284.png)

**Comment by mikrovvelle** [comment] 2020-04-15 14:37
Couple of points:

- Marketplace doesn't allow a change the publisher or extension ID ("mlxprs.mlxprs"). The only alternative would be to pull it and publish under a new ID (we'd risk fragmenting, leaving uninformed users on an old version, and lose all our stats)
- I'd still be ok with getting rid of all "mlxprs" references in the title and text fields. The remaining reference in the ID is mostly under the UX hood.
- Agreed on SJS --> JavaScript, and the opening README text

**Comment by jmakeig** [comment] 2020-04-15 18:59
> I’d still be ok with getting rid of all "mlxprs" references in the title and text fields. The remaining reference in the ID is mostly under the UX hood.

“mlxprs” is an identifier for computers. “MarkLogic VS Code extension” is the name for humans.

**Comment by mikrovvelle** [comment] 2020-04-17 14:59
Any objections to closing this as a duplicate to #31? The Marketplace copy is just a rendering of the top-level README, so this will happen once we release the new version.

**Comment by jmakeig** [comment] 2020-04-17 15:28
Dupe of #31.

**Closed as completed by jmakeig** 2020-04-17 15:28 UTC
