### ISSUE TITLE
Make SJS debug server port configurable

### ISSUE THREAD

**Issue by mikrovvelle** [marklogic/mlxprs#55] opened 2020-04-20 13:08 UTC
There are likely situations where the user will not be running the SJS debug server on port 8002, or it will be re-mapped to a different port for whatever reason. This should be configurable, but still default to 8002.

**Comment by paxtonhare** [comment] 2020-06-19 13:57
Just ran into this.

**Comment by brent-hartwig** [comment] 2021-04-09 19:29
Customer using non-standard ports just hit this as well

**Comment by rjrudin** [comment] 2022-11-29 15:35
Closing as dupe of #97

**Closed as completed by rjrudin** 2022-11-29 15:35 UTC
Labels: connection
